"""add langgraph checkpoints

Revision ID: 2359c09a2a8b
Revises: 5bf44bc1fccf
Create Date: 2025-12-17 20:29:33.591723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2359c09a2a8b'
down_revision: Union[str, Sequence[str], None] = '5bf44bc1fccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('checkpoint_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id', 'key')
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('checkpoint_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id', 'task_id', 'idx')
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('checkpoint_id', sa.String(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('checkpoint', sa.LargeBinary(), nullable=False),
    sa.Column('metadata', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_review_requests_run_id'), table_name='review_requests')
    op.drop_index(op.f('ix_review_requests_status'), table_name='review_requests')
    op.drop_index(op.f('ix_review_requests_thread_id'), table_name='review_requests')
    op.drop_index(op.f('ix_review_requests_workflow_id'), table_name='review_requests')
    op.drop_table('review_requests')
    op.drop_index(op.f('ix_evaluation_runs_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_workflow_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_review_decisions_review_request_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_evaluation_results_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.alter_column('workflow_runs', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_table('evaluation_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.VARCHAR(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('metrics', sqlite.JSON(), nullable=True),
    sa.Column('trace_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_id'), 'evaluation_results', ['id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('review_request_id', sa.VARCHAR(), nullable=False),
    sa.Column('decision', sa.VARCHAR(length=15), nullable=False),
    sa.Column('actor', sa.VARCHAR(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['review_request_id'], ['review_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_review_request_id'), 'review_decisions', ['review_request_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(), nullable=False),
    sa.Column('candidate_version', sa.VARCHAR(), nullable=False),
    sa.Column('deployed_version', sa.VARCHAR(), nullable=True),
    sa.Column('start_ts', sa.DATETIME(), nullable=False),
    sa.Column('end_ts', sa.DATETIME(), nullable=True),
    sa.Column('aggregated_score', sa.FLOAT(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('total_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_workflow_id'), 'evaluation_runs', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_id'), 'evaluation_runs', ['id'], unique=False)
    op.create_table('review_requests',
    sa.Column('workflow_id', sa.VARCHAR(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=False),
    sa.Column('agent_id', sa.VARCHAR(), nullable=False),
    sa.Column('step_name', sa.VARCHAR(), nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), nullable=False),
    sa.Column('checkpoint_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('proposed_action', sqlite.JSON(), nullable=True),
    sa.Column('cost_estimate_usd', sa.FLOAT(), nullable=False),
    sa.Column('risk_level', sa.VARCHAR(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('decision_at', sa.DATETIME(), nullable=True),
    sa.Column('decision_by', sa.VARCHAR(), nullable=True),
    sa.Column('decision_reason', sa.TEXT(), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_requests_workflow_id'), 'review_requests', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_review_requests_thread_id'), 'review_requests', ['thread_id'], unique=False)
    op.create_index(op.f('ix_review_requests_status'), 'review_requests', ['status'], unique=False)
    op.create_index(op.f('ix_review_requests_run_id'), 'review_requests', ['run_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_blobs')
    # ### end Alembic commands ###
