from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List
import uuid

from app.database import get_db
from app.models.run import WorkflowRun
from pydantic import BaseModel
from datetime import datetime

router = APIRouter()

class RunCreate(BaseModel):
    workflow_id: str
    input_data: dict

class RunResponse(BaseModel):
    id: str
    workflow_id: str
    status: str
    input_data: dict
    started_at: datetime

    class Config:
        from_attributes = True

@router.post("", response_model=RunResponse)
async def create_run(run: RunCreate, db: Session = Depends(get_db)):
    db_run = WorkflowRun(
        workflow_id=run.workflow_id,
        status="pending",
        input_data=run.input_data
    )
    # id is generated by UUIDMixin
    db.add(db_run)
    db.commit()
    db.refresh(db_run)
    return db_run

@router.get("", response_model=List[RunResponse])
async def list_runs(db: Session = Depends(get_db)):
    return db.query(WorkflowRun).all()
